version: 2

models:
  - name: dim_customer
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
      - name: name
        tests:
          - not_null

  - name: dim_item
    columns:
      - name: item_id
        tests:
          - not_null
          - unique